rails/music_app/config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: "bands#index"
  
  resources :users, only: [:create, :new, :show, :index] do
    get 'activate', to: 'users#activate', as: :activate, on: :collection
    get 'admin', to: 'users#admin', as: :admin, on: :member
  end

  resource :session, only: [:create, :new, :destroy]
  
  resources :bands do
    resources :albums, only: [:new]
  end
  
  resources :albums, except: [:index, :new] do
    resources :tracks, only: [:new]
  end

  resources :tracks, except: [:index, :new] do
    resources :notes, only: [:create]
  end
  
  resources :notes, only: [:destroy]

  resources :tags do 
    get 'search', to: 'tags#search', as: :search, on: :collection
  end
end

rails/music_app/app/models/band.rb
class Band < ApplicationRecord
  validates :name, presence: true

  has_many :albums, dependent: :destroy
  has_many :tracks, through: :albums, source: :tracks
  has_many :tags, as: :taggable, dependent: :destroy
end

rails/music_app/app/controllers/bands_controller.rb
class BandsController < ApplicationController
  before_action :ensure_logged_in
  before_action :ensure_admin, except: [:index, :show]
  
  def new
    @band = Band.new
  end

  def create
    @band = Band.new(band_params)
    if @band.save
      redirect_to band_url(@band)
    else
      flash.now[:errors] = @band.errors.full_messages
      render :new
    end
  end
  
  def edit
    @band = Band.find(params[:id])
  end
  
  def update
    @band = Band.find(params[:id])
    
    if @band.update(band_params)
      redirect_to band_url(@band)
    else
      flash.now[:errors] = @band.errors.full_messages
      render :edit
    end
  end

  def index
    @bands = Band.all.order(:id)
  end

  def show
    @band = Band.find_by(id: params[:id])
    @albums = @band.albums
  end

  def destroy
    band = Band.find(params[:id])
    band.destroy
    redirect_to bands_url
  end

  private

  def band_params
    params.require(:band).permit(:name)
  end
end

rails/music_app/app/views/bands/_form.html.erb
<% if action == :new %>
  <% action_url = bands_url %>
  <% page_header = "New Band!" %>
<% else %>
  <% action_url = band_url(@band) %>
  <% page_header = "Edit"%>
<% end %>

<%= error_messages(flash.now[:errors]) %>
<h1 class="page-header"><%= page_header %></h1>


<form action="<%= action_url %>" method="post" class="form">
  <%= auth_token %>
  
  <% if action == :edit %>
    <%= patch_hidden_input %>
  <% end %>
  

  <div class="form-div clearfix">
    <label for="name" class="form-label">Name</label>
    <input type="text" class="form-input" name="band[name]" value="<%= @band.name %>">
  </div>

  <div class="form-div clearfix">
    <input type="submit" class="button" value="Submit">
  </div>
</form>

rails/music_app/app/views/bands/edit.html.erb
<%= render 'form', action: :edit %>

rails/music_app/app/views/bands/index.html.erb
<%= error_messages(flash[:errors]) %>

<h1 class="page-header">Bands</h1>

<ul class="main-list clearfix">
  <% @bands.each do |band|%>
    <li class="main-list-item">
      <a href="<%= band_url(band) %>">
          <p><%= band.name %></p>
      </a>
    </li>
  <% end %>
</ul>

<h4 class="sub-header">Links</h4>

<% if current_user.admin %>
  <%= link_to 'New band', new_band_url, class: "button" %>
<% end %>

rails/music_app/app/views/bands/show.html.erb
<h1 class="page-header"><%= @band.name %></h1>

<h4 class="sub-header">Albums</h4>

<% if @albums.empty? %>
  <p>This band has no albums... yet!</p>
<% end %>

<ul class="main-list">
  <% @albums.each do |album| %>
    <li class="main-list-item">
      <a href="<%= album_url(album) %>">
        <p><%= album.title %></p>
      </a>
    </li>
  <% end %>
</ul>

<h4 class="sub-header">Links</h4>
<ul class="link-list">

  
  <% if current_user.admin %>
    <li class="link-list-item">
      <%= link_to 'New Album', new_band_album_url(@band), class: "button" %>
    </li>

    <li class="link-list-item">
      <%= link_to 'Edit Band', edit_band_url(@band), class: "button" %>
    </li>

    <li class="link-list-item">
      <form action="<%= band_url(@band) %>" method="post">
        <%= auth_token %>
        <%= delete_hidden_input %>
        <input type="submit" value="Destroy Band" class="button">
      </form>
    </li>
  <% end %>

  <li class="link-list-item">
    <%= link_to 'All Bands', bands_url, class: "button" %>
  </li>
</ul>