rails/music_app/config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: "bands#index"
  
  resources :users, only: [:create, :new, :show, :index] do
    get 'activate', to: 'users#activate', as: :activate, on: :collection
    get 'admin', to: 'users#admin', as: :admin, on: :member
  end

  resource :session, only: [:create, :new, :destroy]
  
  resources :bands do
    resources :albums, only: [:new]
  end
  
  resources :albums, except: [:index, :new] do
    resources :tracks, only: [:new]
  end

  resources :tracks, except: [:index, :new] do
    resources :notes, only: [:create]
  end
  
  resources :notes, only: [:destroy]

  resources :tags do 
    get 'search', to: 'tags#search', as: :search, on: :collection
  end
end

rails/music_app/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Music App</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css2?family=Bungee+Inline&family=Raleway&display=swap" rel="stylesheet"> 

  </head>

  <body>
    <div class="main-content">
      <header>
        <h1 class="main-logo">MUSIC APP</h1>
        
        <% if signed_in? %>
          <nav class="clearfix">
            <%= link_to 'Take me Home', bands_url, class: "button" %>
            <% if current_user.admin %>
              <%= link_to 'All Users', users_url, class: "button" %>
            <% end %>
            
            <div class="user-detail">
              Logged in as: <%= current_user.email %>
              <form action="<%= session_url %>" method="post">
                <%= auth_token %>
                <%= delete_hidden_input %>
                <input type="submit" class="button" value="Sign Out">
              </form>
            </div>
          </nav>

          <br>
          <br>

          <form action="<%= search_tags_url %>" method="post">
            <%= auth_token %>
            <input type="hidden" name="_method" value="GET">
            <label for="search">Search by tag: </label>
            <input type="input" name="search_term" id="search">

            <label for="model"></label>
            <select name="model" id="model">
              <option value="" selected>Search all types</option>
              <option value="Band">Search Bands</option>
              <option value="Album">Search Albums</option>
              <option value="Track">Search Tracks</option>
            </select>
            <input type="submit" value="Search">

          </form>    
        <% end %>
        
      </header>
      
      <%= yield %>
    </div>
  </body>
</html>