rails/Cats/config/routes.rb
# == Route Map
#
#                     Prefix Verb  URI Pattern                                Controller#Action
#                       cats GET   /cats(.:format)                            cats#index
#                            POST  /cats(.:format)                            cats#create
#                    new_cat GET   /cats/new(.:format)                        cats#new
#                   edit_cat GET   /cats/:id/edit(.:format)                   cats#edit
#                        cat GET   /cats/:id(.:format)                        cats#show
#                            PATCH /cats/:id(.:format)                        cats#update
#                            PUT   /cats/:id(.:format)                        cats#update
# approve_cat_rental_request POST  /cat_rental_requests/:id/approve(.:format) cat_rental_requests#approve
#    deny_cat_rental_request POST  /cat_rental_requests/:id/deny(.:format)    cat_rental_requests#deny
#        cat_rental_requests POST  /cat_rental_requests(.:format)             cat_rental_requests#create
#     new_cat_rental_request GET   /cat_rental_requests/new(.:format)         cat_rental_requests#new

Rails.application.routes.draw do
  resources :cats, only: [:index, :show, :new, :create, :edit, :update]
  resources :cat_rental_requests, only: [:new, :create] do
    member do
      post :approve, to: "cat_rental_requests#approve", as: :approve
      post :deny, to: "cat_rental_requests#deny", as: :deny
    end
  end

  resources :users, only: [:create, :new]
  resource :session, only: [:create, :new, :destroy]
end

rails/Cats/app/models/cat.rb
# == Schema Information
#
# Table name: cats
#
#  id          :bigint           not null, primary key
#  birth_date  :date             not null
#  color       :string           not null
#  name        :string           not null
#  sex         :string(1)        not null
#  description :text             not null
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#
require "action_view"

class Cat < ApplicationRecord
  include ActionView::Helpers::DateHelper

  validates :birth_date, :color, :name, :sex, :description, presence: true
  validates :color, inclusion: { in: %w(yellow black white flower grey), 
    message: "can only be a set of accepted colors" }
  validates :sex, inclusion: { in: [ "M", "F"], 
    messeage: "can only be M or F" }

  has_many :cat_rental_requests,
    primary_key: :id,
    foreign_key: :cat_id,
    class_name: "CatRentalRequest",
    dependent: :destroy

  belongs_to :owner, 
    primary_key: :id,
    foreign_key: :user_id,
    class_name: "User"

  def age
    distance_of_time_in_words_to_now(self.birth_date) + " old"
  end
end

rails/Cats/app/controllers/cats_controller.rb
class CatsController < ApplicationController
  before_action :redirect_if_not_owner, only: [:update, :edit]

  def index
    @cats = Cat.all
    render :index
  end

  def show
    @cat = Cat.find_by(id: params[:id])
    @requests = @cat.cat_rental_requests.includes(:requester).order(:start_date)
    render :show
  end

  def new
    @cat = Cat.new
    render :new
  end

  def create
    @cat = Cat.new(cat_params)
    @cat.user_id = current_user.id

    if @cat.save
      redirect_to cat_url(@cat)
    else
      redirect_to new_cat_url
    end
  end

  def edit
    @cat = Cat.find_by(id: params[:id])
    render :edit
  end

  def update
    @cat = Cat.find_by(id: params[:id])
    if @cat.update_attributes(cat_params)
      redirect_to cat_url(@cat)
    else
      redirect_to edit_cat_url(@cat)
    end
  end

  private

  def cat_params
    params.require(:cat).permit(:name, :sex, :birth_date, :description, :color)
  end
  
  def redirect_if_not_owner
    @cat = Cat.find_by(id: params[:id])
    redirect_to cat_url(@cat) if @cat.user_id != current_user.id
  end
end

rails/Cats/app/views/cats/_cat.html.erb
<li>
  <%= link_to cat.name, cat_url(cat) %>
</li>

rails/Cats/app/views/cats/_form.html.erb
<% if action == :edit %>
  <% path = cat_url(cat)%>
  <% button_text = "Update!" %>
<% else%>
  <% path = cats_url %>
  <% button_text = "Add Cat!" %>
<% end %>



<form action="<%= path %>" method="post">
  <% if action == :edit %>
    <input type="hidden" name="_method" value="PATCH">
  <% end%>

  <label for="name">Name:</label>
  <input type="text" id="name" name="cat[name]" value="<%= cat.name %>">

  <br/>
  <br/>

  <label for="color">Color:</label>
  <select id="color" name="cat[color]">
    <option <%= action == :edit ? "" : "selected" %> disabled>--Please Select--</option>
    <option value="yellow" <%= cat.color == "yellow" ? "selected" : "" %>>Yellow</option>
    <option value="white" <%= cat.color == "white" ? "selected" : "" %>>White</option>
    <option value="black" <%= cat.color == "black" ? "selected" : "" %>>Black</option>
    <option value="flower" <%= cat.color == "flower" ? "selected" : "" %>>Flower</option>
    <option value="grey" <%= cat.color == "grey" ? "selected" : "" %>>Grey</option>
  </select>

  <br/>
  <br/>

  <label for="birth_date">Date of Birth:</label>
  <input type="date" id="birth_date" name="cat[birth_date]" value=<%= cat.birth_date %>>

  <br/>
  <br/>

  <label for="sex">Sex:</label>
    <input type="radio" id ="male" name="cat[sex]" value="M" <%= cat.sex == "M" ? "checked" : "" %>>
    <label for="male">Male</label>
    <input type="radio" id ="Female" name="cat[sex]" value="F" <%= cat.sex == "F" ? "checked" : "" %>>
    <label for="female">Female</label>

  <br/>
  <br/>
  
  <label for="description">Description:</label>
  <textarea id="description" name="cat[description]"><%= cat.description %></textarea>

  <br/>
  <br/>
  <input type="submit" value="<%= button_text %>">
</form>

rails/Cats/app/views/cats/_request.html.erb
<li>
  <%= request.start_date.to_s %> - <%= request.end_date.to_s %> by <%= request.requester.username %> (<%= request.status %>)
  
  <% if current_user.id == owner_id%>

    <form action="<%= approve_cat_rental_request_url(request) %>" method="post">
      <input type="submit" value="APPROVE" >
    </form>

    <form action="<%= deny_cat_rental_request_url(request) %>" method="post">
      <input type="submit" value="DENY" >
    </form>

  <% end %>
</li>

rails/Cats/app/views/cats/edit.html.erb
<h1>Edit a Cat</h1>

<%= render 'form', action: :edit, cat: @cat %>

rails/Cats/app/views/cats/index.html.erb
<a href="<%= new_cat_url %>">Add a new cat</a>
<h1>Welcome to the List of Cats</h1>

<ul>
    <%= render @cats %>

    <!--
    <li>
      <%# @cats.each do |cat| %>
        <a href="/cats/<%# cat.id %>"><%# cat.name %></a>
      <%# end %>
    </li>
    -->
</ul>

rails/Cats/app/views/cats/new.html.erb
<h1>Add a New Cat</h1>

<%= render "form", action: :new, cat: @cat %>

rails/Cats/app/views/cats/show.html.erb
<a href="<%= new_cat_url %>">Add a new cat</a>
<br>
<h1><%= @cat.name %></h1>
<table>
  <thead>
    <tr>
      <th><%= @cat.name %></th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td><strong>Sex</strong></td>
      <td><%= @cat.sex %></td>
    </tr>

    <tr>
      <td><strong>Color</strong></td>
      <td><%= @cat.color %></td>
    </tr>
    
    <tr>
      <td><strong>Age</strong></td>
      <td><%= @cat.age %></td>
    </tr>

    <tr>
      <td><strong>Description</strong></td>
      <td><%= @cat.description %></td>
    </tr>
  </tbody>
</table>

<br>

<% if current_user.id != @cat.user_id %>
  <a href="<%= new_cat_rental_request_url %>">Rent the cat</a>
<% end%>

<br>
<br>

<label for="request_list">Existing Requests</label>
<ul id="request_list">
  <% @requests.each do |request| %>
    <%= render "request", request: request, owner_id: @cat.user_id %>
  <% end %>
</ul>