rails/Cats/config/routes.rb
# == Route Map
#
#                     Prefix Verb  URI Pattern                                Controller#Action
#                       cats GET   /cats(.:format)                            cats#index
#                            POST  /cats(.:format)                            cats#create
#                    new_cat GET   /cats/new(.:format)                        cats#new
#                   edit_cat GET   /cats/:id/edit(.:format)                   cats#edit
#                        cat GET   /cats/:id(.:format)                        cats#show
#                            PATCH /cats/:id(.:format)                        cats#update
#                            PUT   /cats/:id(.:format)                        cats#update
# approve_cat_rental_request POST  /cat_rental_requests/:id/approve(.:format) cat_rental_requests#approve
#    deny_cat_rental_request POST  /cat_rental_requests/:id/deny(.:format)    cat_rental_requests#deny
#        cat_rental_requests POST  /cat_rental_requests(.:format)             cat_rental_requests#create
#     new_cat_rental_request GET   /cat_rental_requests/new(.:format)         cat_rental_requests#new

Rails.application.routes.draw do
  resources :cats, only: [:index, :show, :new, :create, :edit, :update]
  resources :cat_rental_requests, only: [:new, :create] do
    member do
      post :approve, to: "cat_rental_requests#approve", as: :approve
      post :deny, to: "cat_rental_requests#deny", as: :deny
    end
  end

  resources :users, only: [:create, :new]
  resource :session, only: [:create, :new, :destroy]
end

rails/Cats/app/views/layouts/_form.html.erb
<% if action == :sign_up %>
  <% action_url = users_url %>
  <% message = "Sign Up!" %>
<% else %>
  <% action_url = session_url %>
  <% message = "Sign In!" %>
<% end %>

<form action="<%= action_url %>" method="post">
  <input 
    type="hidden"
    name="authenticity_token"
    value="<%= form_authenticity_token %>">

  <label for="username">username: </label>
  <input type="text" name="user[username]" value="<%= @user.username %>">

  <br>
  <br>

  <label for="password">password: </label>
  <input type="password" name="user[password]">

  <br>
  <br>

  <input type="submit" value="<%= message %>">
</form>

rails/Cats/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Cats</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%# stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%#= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header>
      <% if current_user %>
        <h3>hello, <%= current_user.username %></h3>
        <form action="<%= session_url %>" method="post">
          <input type="hidden" name="authenticity_token" value=<%= form_authenticity_token %>>
          <input type="hidden" name="_method" value="DELETE">
          <input type="submit" value="Log out">
        </form>
      <% else %>
        <a href="<%= new_session_url %>">Log in</a>
        <a href="<%= new_user_url %>">Sign up</a>
      <% end %>
    </header>
    <%= yield %>
  </body>
</html>